### ISSUE TITLE
Native support for sending emails

### ISSUE THREAD

**Issue by shpakovski** [qutheory/red-feedback#29]
Hello, I’m curious about one missed feature.

It is great that you support Databases natively: I assume they’re installed on the same server where the Vapor app is running.

In addition to data though, a modern backend usually needs an email provider. As an example, I’m using [Mailgun](https://www.mailgun.com) with a nice open-source [service component](https://github.com/vapor-community/VaporMailgunService) for Vapor.

Ideally, we need a new entry like “Email” next to NGINX and Swift on the Tools page, or a new sidebar item “Email” below Databases.

Is this something you may consider for the future? What is your suggestion if not? Thanks in advance!

**Comment by joscdk** [comment]
@shpakovski Hi, thank you for the feedback.

For databases, it's installed on the server you install it. So you can either install it on the same server as your Vapor app, or create a new server through Red to install the database server, we plan on making videos and documentation on how to setup various scenarios :)

For Email, i am not sure what you mean, but there are actually installed Sendmail on the server, so you can send email from the server. However a couple of things, you would need a Vapor package to support native SMTP email, it's not built into Vapor.
Besides that, setting up and maintaining a mailserver is NOT an easy task, due to maintaining everything in terms of spamfilters, blacklists, configuration and much more.
You also need to handle bounces correctly, monitor mail score etc. This is unfortunately not something in the scope for Vapor Red to do for you, since there are services handling it for you, and a lot better than we can do :)

Our general recommendation is to use Mailgun, Sendgrid or Amazon SES, since these services maintain all of these things for you. But if you want to try it yourself, there are installed Sendmail on the server, but not really in a state it should be used for production usage.

**Comment by shpakovski** [comment]
> Our general recommendation is to use Mailgun, Sendgrid or Amazon SES.

Thanks Jonas, I think I was looking for the answer like this 😄
